pyproject.toml

build(issue-2): Project initial structure.

---

poetry.lock
pyproject.toml

feat(issue-5): Instalado dependências de projeto.

---

tests/test_main_api.py
todo/app.py

feat(issue6): Iniciada a API base e escrito os primeiros teste.

---

.gitignore
postgres/Dockerfile
postgres/create-database.sh

feat(issue7): Preparar Postgres como serviço.

---

.dockerignore
poetry.lock
pyproject.toml

feat(issue15): Instalado e configurado ferramenta de cobertura de testes, e criado .dockerignore.

---

.flake8
poetry.lock
pyproject.toml

feat(issue9): Automatizadas tarefas repetitivas com TaskiPy

---

poetry.lock
pyproject.toml
todo/models/__init__.py
todo/models/user.py

feat(issue20): Modelado o banco de Users

---

poetry.lock
pyproject.toml
todo/config.py
todo/default.toml

feat(issue21): Ajustadas as configurações do projeto com Dynaconf.

---

todo/db.py

feat(issue22): Criada a conexão com o Banco de Dados

---

pyproject.toml

fix(issue29): Corrigido problema no pyproject.toml para instalação interna do projeto.

---

todo/config.py
todo/db.py

fix(issue30): Corrigido o problema do default.toml para usuo correto do Dynaconf.

---

poetry.lock
pyproject.toml
todo/cli.py

feat(issue26): Iniciad a implementação da ferramenta de CLI com shell e user-list.

---

poetry.lock
pyproject.toml
todo/cli.py
todo/models/__init__.py
todo/models/user.py

feat(issue36): Instlada lib python-slugify e criada função geradora de user-name.

---

todo/cli.py

feat(issue40): Implementado comando create-user em nossa CLI.

---

todo/db.py

feat(issue42): Criada injeção de dependência de session para o fastAPI.

---

todo/app.py
todo/models/__init__.py
todo/routes/__init__.py
todo/routes/user.py

feat(issue43): Criadas as views e rotas de User.

---

poetry.lock
pyproject.toml
todo/routes/user.py

feat(issue50): Ajustada configuração do Flake8.

---

todo/models/__init__.py
todo/models/user.py
todo/routes/user.py

feat(issue52): Melhorada a rota de User com a função get_user.

---

poetry.lock
pyproject.toml
todo/routes/__init__.py
todo/routes/auth.py

feat(issue56): Criadas rotas para token e refresh token.

---

poetry.lock
pyproject.toml
todo/models/user.py

todo-project-74 Criada  validação para o e-mail, usando libs Pydantic e email-validator.

---

docker-compose.yml
postgres/Dockerfile
tests.sh
todo/cli.py
todo/db.py

fix(issue-79): Ajustado docke-compose para usar banco de dados nos testes e criada a PipeLine.
